import { createServer } from 'node:http';
import { readFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHmac } from 'node:crypto';

const root = process.cwd(); mkdirSync(join(root,'data'),{recursive:true});
const db = new DatabaseSync(join(root,'data','trendyshop.sqlite'));
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, image TEXT NOT NULL, price INTEGER NOT NULL CHECK(price>=0), discount INTEGER NOT NULL DEFAULT 0 CHECK(discount BETWEEN 0 AND 100), stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0), sold INTEGER NOT NULL DEFAULT 0 CHECK(sold>=0), featured INTEGER NOT NULL DEFAULT 0, created TEXT NOT NULL, updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_images (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, url TEXT NOT NULL, sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL, email TEXT, city TEXT NOT NULL, address TEXT NOT NULL, note TEXT, total INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'Pending', payment_method TEXT NOT NULL DEFAULT 'COD', created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id TEXT NOT NULL, name TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), price INTEGER NOT NULL, original_price INTEGER NOT NULL, discount INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admins (id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);`);
const secret=process.env.SESSION_SECRET||'change-this-secret-in-production';
const hash=p=>{const salt='trendyshop-salt';return scryptSync(p,salt,32).toString('hex')};
if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get())db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(process.env.ADMIN_EMAIL||'admin@trendyshop.pk',hash(process.env.ADMIN_PASSWORD||'change-me'));
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}})});
function state(){const products=db.prepare('SELECT id,name,description,category,image,price,discount,stock,sold,featured,created FROM products ORDER BY created DESC').all().map(p=>({...p,featured:!!p.featured}));const orders=db.prepare('SELECT * FROM orders ORDER BY created').all().map(o=>({...o,items:db.prepare('SELECT product_id id,name,quantity qty,price FROM order_items WHERE order_id=?').all(o.id)}));let sale=JSON.parse(db.prepare("SELECT value FROM settings WHERE key='sale'").get()?.value||'{"active":false,"title":"","description":"","percent":0}');let contact=JSON.parse(db.prepare("SELECT value FROM settings WHERE key='contact'").get()?.value||'{"email":"","phone":"","whatsapp":"","location":"","hours":""}');return {products,orders,settings:{sale,contact}}}
function putState(s){db.exec('BEGIN');try{db.exec('DELETE FROM order_items; DELETE FROM orders; DELETE FROM product_images; DELETE FROM products; DELETE FROM categories;');const now=new Date().toISOString();const ip=db.prepare('INSERT INTO products(id,name,description,category,image,price,discount,stock,sold,featured,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');for(const p of s.products||[]){ip.run(p.id,p.name,p.description||'',p.category||'Other',p.image||'',Number(p.price)||0,Number(p.discount)||0,Number(p.stock)||0,Number(p.sold)||0,p.featured?1:0,p.created||now,now);db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)').run(p.category||'Other');}const io=db.prepare('INSERT INTO orders(id,name,phone,email,city,address,note,total,status,payment_method,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)');const ii=db.prepare('INSERT INTO order_items(order_id,product_id,name,quantity,price,original_price,discount) VALUES(?,?,?,?,?,?,?)');for(const o of s.orders||[]){io.run(o.id,o.name,o.phone,o.email||'',o.city,o.address,o.note||'',o.total,o.status||'Pending','COD',o.created||now);for(const i of o.items||[])ii.run(o.id,i.id,i.name,i.qty,i.price,i.original_price||i.price,i.discount||0)}for(const [k,v] of Object.entries(s.settings||{}))db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').run(k,JSON.stringify(v));db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
function token(email){return createHmac('sha256',secret).update(email+'|'+Date.now()).digest('hex')+'.'+email}function valid(t){return !!t&&t.split('.')[1]&&createHmac('sha256',secret).update(t.split('.')[1]).digest('hex')===t.split('.')[0]}
const server=createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(req.url==='/api/bootstrap'&&req.method==='GET')return json(res,200,state());if(req.url==='/api/state'&&req.method==='PUT'){putState(await body(req));return json(res,200,{ok:true})}if(req.url==='/api/admin/login'&&req.method==='POST'){const b=await body(req),a=db.prepare('SELECT * FROM admins WHERE email=?').get(b.email);if(!a||a.password_hash!==hash(b.password))return json(res,401,{error:'Invalid credentials'});return json(res,200,{token:token(a.email)})}if(req.url.startsWith('/api/admin')&&!valid(req.headers.authorization?.replace('Bearer ','')))return json(res,401,{error:'Unauthorized'});if(req.url==='/api/health')return json(res,200,{ok:true,database:'sqlite'});json(res,404,{error:'Not found'})}catch(e){console.error(e);json(res,400,{error:'Request could not be completed'})}});
server.listen(process.env.PORT||8787,'0.0.0.0',()=>console.log('Trendy Shop API running on port '+(process.env.PORT||8787)));
