import { createServer } from 'node:http';
import { readFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { scryptSync, createHmac, randomUUID } from 'node:crypto';
const root=process.cwd(); mkdirSync(join(root,'data'),{recursive:true}); const db=new DatabaseSync(join(root,'data','trendyshop.sqlite'));
db.exec(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL); CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,image TEXT NOT NULL,price INTEGER NOT NULL CHECK(price>=0),discount INTEGER NOT NULL DEFAULT 0 CHECK(discount BETWEEN 0 AND 100),stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),sold INTEGER NOT NULL DEFAULT 0 CHECK(sold>=0),featured INTEGER NOT NULL DEFAULT 0,created TEXT NOT NULL,updated TEXT NOT NULL); CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,url TEXT NOT NULL,sort_order INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,city TEXT NOT NULL,address TEXT NOT NULL,note TEXT,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'Pending',payment_method TEXT NOT NULL DEFAULT 'COD',created TEXT NOT NULL); CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,quantity INTEGER NOT NULL,price INTEGER NOT NULL,original_price INTEGER NOT NULL,discount INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
const env=(k,d)=>process.env[k]||d;const hash=p=>scryptSync(String(p),env('PASSWORD_SALT','trendyshop-salt'),32).toString('hex');const secret=env('SESSION_SECRET','replace-this-session-secret');
if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get())db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(env('ADMIN_EMAIL','admin@trendyshop.pk'),hash(env('ADMIN_PASSWORD','change-me')));
if(!db.prepare('SELECT 1 FROM settings WHERE key=?').get('sale'))db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').run('sale',JSON.stringify({active:false,title:'Mega Sale',description:'Fresh picks at better prices.',percent:20}));
if(!db.prepare('SELECT 1 FROM settings WHERE key=?').get('contact'))db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').run('contact',JSON.stringify({email:'',phone:'',whatsapp:'',location:'',hours:''}));
const seed=[['p-demo-1','Luna Mini Shoulder Bag','A softly structured everyday bag for your essentials.','Fashion','https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',4200,15,18,42,1],['p-demo-2','Arc Wireless Headphones','Rich balanced sound and all-day comfort.','Tech','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',11500,10,24,91,1]];
if(!db.prepare('SELECT 1 FROM products LIMIT 1').get()){const q=db.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');const now=new Date().toISOString();for(const x of seed){q.run(x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],x[8],x[9],now,now);db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)').run(x[3])}}
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))};const readBody=req=>new Promise((ok,no)=>{let s='';req.on('data',x=>{s+=x;if(s.length>1e6)no(Error('Payload too large'))});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})});const token=email=>createHmac('sha256',secret).update(email+'|trendy').digest('hex')+'.'+email;const auth=req=>{const t=(req.headers.authorization||'').replace('Bearer ','');if(!t)return false;const [sig,email]=t.split('.');return !!email&&sig===createHmac('sha256',secret).update(email+'|trendy').digest('hex')&&!!db.prepare('SELECT 1 FROM admins WHERE email=?').get(email)};
function sale(){return JSON.parse(db.prepare('SELECT value FROM settings WHERE key=?').get('sale').value)}function productRows(){return db.prepare('SELECT * FROM products ORDER BY created DESC').all().map(p=>({...p,featured:!!p.featured,remaining:p.stock}))}function state(){const orders=db.prepare('SELECT * FROM orders ORDER BY created DESC').all().map(o=>({...o,items:db.prepare('SELECT product_id id,name,quantity qty,price,original_price,discount FROM order_items WHERE order_id=?').all(o.id)}));return{products:productRows(),orders,settings:{sale:sale(),contact:JSON.parse(db.prepare('SELECT value FROM settings WHERE key=?').get('contact').value)}}}
function calc(p,s){const d=s.active?s.percent:p.discount;return{discount:d,final:Math.round(p.price*(1-d/100))}}
function createOrder(b){if(!b.name||!b.phone||!b.city||!b.address||!Array.isArray(b.items)||!b.items.length)throw Error('Missing required order details');const s=sale(),items=[];db.exec('BEGIN IMMEDIATE');try{for(const i of b.items){const qty=Number(i.quantity);if(!Number.isInteger(qty)||qty<1)throw Error('Invalid quantity');const p=db.prepare('SELECT * FROM products WHERE id=?').get(i.product_id);if(!p||p.stock<qty)throw Error(`Insufficient stock for ${p?.name||'product'}`);const c=calc(p,s);items.push({p,qty,c})}const total=items.reduce((n,x)=>n+x.c.final*x.qty,0),id='TS-'+Date.now().toString().slice(-8),now=new Date().toISOString();db.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,b.name,b.phone,b.email||'',b.city,b.address,b.note||'',total,'Pending','COD',now);const oi=db.prepare('INSERT INTO order_items(order_id,product_id,name,quantity,price,original_price,discount) VALUES(?,?,?,?,?,?,?)');const up=db.prepare('UPDATE products SET stock=stock-?,sold=sold+?,updated=? WHERE id=?');for(const x of items){oi.run(id,x.p.id,x.p.name,x.qty,x.c.final,x.p.price,x.c.discount);up.run(x.qty,x.qty,now,x.p.id)}db.exec('COMMIT');return{...db.prepare('SELECT * FROM orders WHERE id=?').get(id),items:items.map(x=>({id:x.p.id,name:x.p.name,qty:x.qty,price:x.c.final}))}}catch(e){db.exec('ROLLBACK');throw e}}
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return json(res,200,{ok:true,database:'sqlite'});if(u.pathname==='/api/admin/login'&&req.method==='POST'){const b=await readBody(req),a=db.prepare('SELECT * FROM admins WHERE email=?').get(b.email);if(!a||a.password_hash!==hash(b.password))return json(res,401,{error:'Invalid credentials'});return json(res,200,{token:token(a.email)})}if(u.pathname==='/api/bootstrap'&&req.method==='GET')return json(res,200,state());if(u.pathname==='/api/orders'&&req.method==='POST')return json(res,201,createOrder(await readBody(req)));if(u.pathname==='/api/admin/orders'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,state().orders)}if(u.pathname==='/api/admin/products'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const b=await readBody(req);if(!b.name||!b.category||!b.image||!Number.isFinite(+b.price)||!Number.isInteger(+b.stock)||+b.price<0||+b.stock<0||+b.discount<0||+b.discount>100)return json(res,422,{error:'Invalid product data'});const id='p-'+randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,b.name,b.description||'',b.category,b.image,+b.price,+b.discount||0,+b.stock,0,b.featured?1:0,now,now);db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)').run(b.category);return json(res,201,db.prepare('SELECT * FROM products WHERE id=?').get(id))}if(u.pathname.startsWith('/api/admin/products/')&&req.method==='DELETE'){if(!auth(req))return json(res,401,{error:'Unauthorized'});db.prepare('DELETE FROM products WHERE id=?').run(u.pathname.split('/').pop());return json(res,200,{ok:true})}if(u.pathname==='/api/admin/products'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,productRows())}if(u.pathname==='/api/admin/settings'&&req.method==='PUT'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const b=await readBody(req);for(const [k,v] of Object.entries(b))db.prepare('INSERT OR REPLACE INTO settings VALUES(?,?)').run(k,JSON.stringify(v));return json(res,200,state().settings)}if(req.method==='GET'){let file=u.pathname==='/'?'index.html':u.pathname.slice(1),full=join(root,file);if(!existsSync(full))full=join(root,'index.html');const type=extname(full)==='.css'?'text/css':extname(full)==='.js'?'text/javascript':'text/html';res.writeHead(200,{'Content-Type':type});return res.end(readFileSync(full))}return json(res,404,{error:'Not found'})}catch(e){console.error(e);return json(res,400,{error:e.message||'Request failed'})}});server.listen(env('PORT','8787'),'0.0.0.0',()=>console.log('Trendy Shop running at http://localhost:'+env('PORT','8787')));
